### PR TITLE
Add/tesult Implementation

### PR DESCRIPTION
**Pull request by alvitazwar**

### CODE REVIEW

**Review by pooja-muchandikar — COMMENTED** [review]
@alvitazwar

- Remove Artifacts folder its not required
- Remove Playwright-report folder its not requried
- Remove all commented code from `playwright-config.ts` file

**Comment by alvitazwar** [comment]
@pooja-muchandikar  I addressed all the feedbacks please check now

**Review by pooja-muchandikar — COMMENTED** [review]
@alvitazwar Commented code to be removed https://github.com/rtCamp/wp-menu-custom-fields/blob/add/tesult/tests/e2e-playwright/playwright.config.ts#L54

**Comment by alvitazwar** [comment]
@pooja-muchandikar  Removed the commented code

**Review by pooja-muchandikar — APPROVED** [review]

**Pull request merged**
