### PR TITLE
Update branch on yml file

### PR DESCRIPTION
**Pull request by pooja-muchandikar**

### CODE REVIEW

**Review by juhi123 — COMMENTED** [review]
Looks good

**Review by juhi123 — APPROVED** [review]

**Comment by juhi123** [comment]
Do send the PR to master also

**Comment by pooja-muchandikar** [comment]
@juhi123 
The yml file is updated and master branch is also added there. So test cases will run if any PR is raised against master as well. Still, do we need to merge the tests in master?

**Comment by juhi123** [comment]
It's better to keep branches synced and updated

**Comment by pooja-muchandikar** [comment]
noted

**Pull request merged**
